title: Vishwa Viswanath
theme: jekyll-theme-minimal
# Data Scientist
### Skills: SciKit Learn, Hugging Face, Python, Program Management

### Work Experience
Data Analytics at Springboard
Data Analytics at CFR
